### ISSUE TITLE
[QUESTION] PHP

### ISSUE THREAD

**Issue by Willoxey** [larryTheCoder/ASkyBlock#11]
Hey!
I used to use your SkyWars plugin. And i saw your other projects that seem to be very complete like this one.
Will you be doing any skyblock plugin for pocketmine users?

**Comment by larryTheCoder** [comment]
No and never, PHP is bad in multi-threading environment.  Pocketmine is good, their plugins are also good, I just don't like PHP ways of how things work. I tried to port this plugin into pocketmine once, and realized its quite impossible to port it. I'm sure, other dev may want to port this, for those who wanted to waste their time porting my plugins _that are already exists_, go on

Use Nukkit Software, the controversy made by someone saying its bad or etc in pmmp discord server is utterly nonsense and lack of general knowledge.

**Comment by larryTheCoder** [comment]
### *-- Probably*
