### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by Gtafgu** [larryTheCoder/ASkyBlock#13]
If a player creates an island, you will be teleported in 2 seconds, but you will not be teleported and cannot go to the island, but with op you can

**Comment by larryTheCoder** [comment]
This issue has already fixed in our master branch, however I didn't release to update due to some bugs and issues. However if you hesitate, try to download it in my [jenkins server here](https://jenkins.potatohome.xyz/job/ASkyBlock)

**Comment by Gtafgu** [comment]
Thank You

**Comment by Gtafgu** [comment]
one can open the chest on another island
