### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Papadoubulus** [larryTheCoder/ASkyBlock#17]
if you have pvp off you can no longer kill monsters if you turn pvp on again you can kill monsters

**Comment by larryTheCoder** [comment]
Well this bug is really weird, I will try to test it again, you are using MobPlugin for this?

**Comment by Papadoubulus** [comment]
I am currently using https://cloudburstmc.org/resources/mobplugin.3/

**Comment by Papadoubulus** [comment]
@larryTheCoder and did you test it or did I do something wrong?

**Comment by Papadoubulus** [comment]
I thank you for always fixing the bugs

**Comment by larryTheCoder** [comment]
Well, I haven't tested it yet with MobPlugin but I will do my best to fix it :)

**Comment by Papadoubulus** [comment]
Thank you!
