### ISSUE TITLE
cant download from github

### ISSUE THREAD

**Issue by blank826** [larryTheCoder/ASkyBlock#5]
hi man ,i find this plugin from NukkitX.But i cant download from you github.

**Comment by larryTheCoder** [comment]
There is an issue with the Jenkins server, perhaps take youself some time so my friend could solve this out

**Comment by blank826** [comment]
ok
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Adam Matthew"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 下午3:19
收件人:&nbsp;"larryTheCoder/ASkyBlock"<ASkyBlock@noreply.github.com&gt;;
抄送:&nbsp;"゛欺騙、有著不得已的笑容"<798173733@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [larryTheCoder/ASkyBlock] cant download from github (#5)





 
There is an issue with the Jenkins server, perhaps take youself some time so my friend could solve this out

**Comment by larryTheCoder** [comment]
The server is up now.
