### ISSUE TITLE
Revise back all the config files to make them official

### ISSUE THREAD

**Issue by good777LUCKY** [larryTheCoder/ASkyBlock#7]
It says it is default is false because it highly changes the gameplay
https://github.com/larryTheCoder/ASkyBlock/blob/2b0b34e48c88948d5e68ab92a26c7a5e89d78fde/src/main/resources/config.yml#L244
but default value of config was
https://github.com/larryTheCoder/ASkyBlock/blob/2b0b34e48c88948d5e68ab92a26c7a5e89d78fde/src/main/resources/config.yml#L245

**Comment by larryTheCoder** [comment]
There is a lot of rewrite that needs to be done, the config files will be revised later on.
