### ISSUE TITLE
Magiccobblegen doesn't work prefectly

### ISSUE THREAD

**Issue by tuilakhanh** [larryTheCoder/ASkyBlock#9]
Magiccobblegen only works when lava is above water

Video: https://photos.app.goo.gl/vuMYWavQN39TpZPi9

**Comment by larryTheCoder** [comment]
Hmm, you are right, I tested it today and it seems like the block don't update within x-z axis.
I will try to fix this issue first.

**Comment by tuilakhanh** [comment]
@larryTheCoder Should you add the water + fence option. It is friendly and keeps obsidian can be generate

**Comment by larryTheCoder** [comment]
Does that wont cause any problems to the player that "accidentally" flowed the water to that fences?

**Comment by tuilakhanh** [comment]
It doesn't have a problem. I used to use it on my server and and players like it more than water + lava

It is just an option If your server doesn't like it, it can be disabled in config

**Comment by larryTheCoder** [comment]
> it can be disabled in config

This is what I want to hear, well, soon it will be implemented 👍

**Comment by tuilakhanh** [comment]
Great I'll wait for it :D

**Comment by larryTheCoder** [comment]
@tuilakhanh This 67832c4fbc73b2cf8df9065cd0a5c55d475813d8 build should be able to generate Obsidian while keeping Magic cobble generator on.

**Comment by tuilakhanh** [comment]
@larryTheCoder nice

I will test more and find some bug
